steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'docker_pipelines/Dockerfile', '-t', '${_TAG}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_TAG}']

options:
  machineType: 'E2_HIGHCPU_32'

substitutions:
  _TAG: 'override-this'

