version: "3.8"

services:
  voice-assistant-service:
    build: .
    ports:
      - "8082:8080"
    environment:
      - PORT=8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4o
    networks:
      - cleanapp-network

networks:
  cleanapp-network:
    driver: bridge
