[package]
name = "stxn_kickoff"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
ethers = { version = "2.0.14", features = ["ws"] }
fatal = "0.1.1"
keccak-hash = "0.11.0"
tokio = { version = "1.41.0", features = ["full"] }
