version: '3.8'

services:
  report-processor:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=server
      - DB_PASSWORD=secret_app
      - DB_NAME=cleanapp
      - PORT=8081
      - AUTH_SERVICE_URL=http://auth-service:8080
      - LOG_LEVEL=info
    depends_on:
      - db
      - auth-service
    restart: unless-stopped
    networks:
      - cleanapp-network

  auth-service:
    build: ../auth-service
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=server
      - DB_PASSWORD=secret_app
      - DB_NAME=cleanapp
      - PORT=8080
      - JWT_SECRET=your-secret-key-here
      - LOG_LEVEL=info
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - cleanapp-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=cleanapp
      - MYSQL_USER=server
      - MYSQL_PASSWORD=secret_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - cleanapp-network

volumes:
  mysql_data:

networks:
  cleanapp-network:
    driver: bridge 