version: '3.8'

services:
  face-detector:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DEBUG=true
      - PORT=5000
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
      - MAX_IMAGE_SIZE=10485760
      - ALLOWED_IMAGE_TYPES=jpg,jpeg,png,gif,bmp
      - IMAGE_QUALITY=85
      - FACE_DETECTION_CONFIDENCE=0.5
      - BLUR_STRENGTH=15
      - PII_DETECTION_ENABLED=true
      - PII_DETECTION_CONFIDENCE=0.7
      - UPLOAD_FOLDER=/tmp/uploads
      - MAX_UPLOAD_FILES=10
      - HEALTH_CHECK_ENABLED=true
    volumes:
      - .:/app
      - uploads:/tmp/uploads
    restart: unless-stopped

volumes:
  uploads:
