version: '3.8'

services:
  areas-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=cleanapp
      - DB_USER=server
      - DB_PASSWORD=secret
    networks:
      - cleanapp-network

networks:
  cleanapp-network:
    driver: bridge 