version: '3.8'

services:
  areas-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DB=cleanapp
      - MYSQL_PASSWORD=secret
    networks:
      - cleanapp-network

networks:
  cleanapp-network:
    driver: bridge 