version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cleanapp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cleanapp
      MYSQL_USER: cleanapp_user
      MYSQL_PASSWORD: cleanapp_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: customer_service
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_USER: cleanapp_user
      DB_PASSWORD: cleanapp_password
      DB_HOST: mysql
      DB_PORT: 3306
      ENCRYPTION_KEY: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
      JWT_SECRET: "your-super-secret-jwt-key-replace-in-production"
      PORT: 8080
      TRUSTED_PROXIES: "127.0.0.1,::1"
      # OAuth providers would be configured here in production
    depends_on:
      mysql:
        condition: service_healthy
    command: go run main.go

volumes:
  mysql_data:
